[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { path = "../api" }
dioxus = { workspace = true, features = ["router", "web"] }
dioxus-sdk = { version = "0.6.0", features = ["storage", "timing"] }
futures = "0.3.31"
gloo-timers = { version = "0.3.0", features = ["futures"] }

[dev-dependencies]
insta = "1.43.1"
dioxus = { workspace = true, features = ["ssr"] }

[features]
default = []
web = ["dioxus/web", "api/web"]
server = ["dioxus/server", "api/server"]
