image: openjdk:8

before_script:
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -yqq
  - apt-get install sbt -yqq
  - sbt sbtVersion

test:
  script:
    - sbt clean coverage test coverageReport coverageAggregate doc
  artifacts:
    paths:
      - target/scala-2.12/scoverage-report/
      - core/target/scala-3.2.0/api/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv target/scala-2.12/scoverage-report/ public/coverage
    - mv core/target/scala-3.2.0/api/ public/api
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
