[workspace]
resolver = "2"
members = [
    "packages/backend",
    "packages/dto",
    "packages/api",
    "packages/ui",
    "packages/frontend",
    "packages/entrypoint"
]

[workspace.dependencies]
dioxus = "0.7.0-rc.3"
dioxus-sdk = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }

api = { path = "packages/api" }
backend = { path = "packages/backend" }
dto = { path = "packages/dto" }
ui = { path = "packages/ui" }
frontend = { path = "packages/frontend" }
