[package]
name = "cribbage"
version = "0.2.27"
edition = "2024"

[dependencies]
# axum = { version = "0.7", optional = true, features = ["macros"] }
# console_error_panic_hook = "0.1"
# leptos = { version = "0.6", features = ["nightly"] }
# leptos_axum = { version = "0.6", optional = true }
# leptos_meta = { version = "0.6", features = ["nightly"] }
# leptos_router = { version = "0.6", features = ["nightly"] }
# server_fn = { version = "0.6", optional = true }
# tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
# tower = { version = "0.4", optional = true }
# tower-http = { version = "0.5", features = ["fs"], optional = true }
# wasm-bindgen = "=0.2.92"
thiserror = "1"
# tracing = { version = "0.1", optional = true }
# http = "1"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
# sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "any", "sqlite"], optional = true }
enum-iterator = "2.0.0"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# dotenv = { version = "0.15", optional = true }
# axum_session = { version = "0.14", optional = true }
# axum-extra = { version = "0.9", optional = true }
# futures = "0.3.30"
itertools = "0.13.0"
# thaw = "0.3.2"

[dev-dependencies]
pretty_assertions = "1.4.1"
