[workspace]
resolver = "2"
members = [
    "packages/ui",
    "packages/web",
    # "packages/desktop",
    # "packages/mobile",
    "packages/api",
    "packages/server",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "BSD-3"

[workspace.dependencies]
dioxus = { version = "0.7.1" }
dioxus-sdk = { git = "https://github.com/ealmloff/dioxus-std", branch = "0.7" }

ui = { path = "packages/ui" }
api = { path = "packages/api" }
server = { path = "packages/server" }
