[package]
name = "entrypoint"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
frontend = { path = "../frontend" }
backend = { path = "../backend", optional = true }
tokio = { version = "1.45.0", features = ["full"], optional = true }
dotenvy = { version = "0.15.7", optional = true }

[features]
default = []
web = ["dioxus/web", "frontend/web"]
server = [
    "dioxus/server",
    "backend/server",
    "frontend/server",
    "dep:tokio",
    "dep:dotenvy",
]
