services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: cribbage
        restart: unless-stopped

    cribbage:
        image: nigeleke/cribbage:latest
        container_name: cribbage
        depends_on:
            - postgres
        environment:
            DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/cribbage"
            RUST_LOG: info
            PORT: 8080
        ports:
            - "8080"
        restart: unless-stopped
