[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-iterator = "2.1.0"
itertools = "0.14.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["v4", "serde"] }

[dev-dependencies]
insta = { version = "1.43.1", features = ["filters"] }
pretty_assertions = "1.4.1"

[lints]
clippy.all = "deny"
clippy.nursery = "warn"
clippy.unwrap_used = "forbid"
clippy.expect_used = "allow"
