pages = [{"l":"index.html#","e":false,"i":"","n":"cribbage-core","t":"cribbage-core","d":"","k":"static"},
{"l":"cribbage.html#","e":false,"i":"","n":"cribbage","t":"cribbage","d":"","k":"package"},
{"l":"cribbage.html#AllLaidCardCount-0","e":false,"i":"","n":"AllLaidCardCount","t":"AllLaidCardCount: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#CardsDealtPerHand-0","e":false,"i":"","n":"CardsDealtPerHand","t":"CardsDealtPerHand: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#CardsKeptPerHand-0","e":false,"i":"","n":"CardsKeptPerHand","t":"CardsKeptPerHand: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#CardsRequiredInCrib-0","e":false,"i":"","n":"CardsRequiredInCrib","t":"CardsRequiredInCrib: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#NumberOfPlayersInGame-0","e":false,"i":"","n":"NumberOfPlayersInGame","t":"NumberOfPlayersInGame: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#PlayTarget-0","e":false,"i":"","n":"PlayTarget","t":"PlayTarget: Int","d":"cribbage","k":"val"},
{"l":"cribbage.html#WinningScore-0","e":false,"i":"","n":"WinningScore","t":"WinningScore: Int","d":"cribbage","k":"val"},
{"l":"cribbage/Cribbage.html#","e":false,"i":"","n":"Cribbage","t":"Cribbage(players: Set[Player], deck: Deck)","d":"cribbage","k":"class"},
{"l":"cribbage/Cribbage$.html#","e":false,"i":"","n":"Cribbage","t":"Cribbage","d":"cribbage","k":"object"},
{"l":"cribbage/Cribbage$.html#dealFirstHand-0","e":false,"i":"","n":"dealFirstHand","t":"dealFirstHand: Decided => Discarding","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#discardToCrib-fffff58b","e":false,"i":"","n":"discardToCrib","t":"discardToCrib(player: Player, discards: Seq[Card]): Discarding => Discarding | Playing | Finished","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#makeDraw-0","e":false,"i":"","n":"makeDraw","t":"makeDraw: Cribbage => Draw","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#newGame-0","e":false,"i":"","n":"newGame","t":"newGame: Cribbage","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#pass-fffff1d6","e":false,"i":"","n":"pass","t":"pass(player: Player): Playing => Playing | Finished","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#play-fffff22e","e":false,"i":"","n":"play","t":"play(player: Player, card: Card): Playing => Playing | Discarding | Finished","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/Cribbage$.html#redraw-0","e":false,"i":"","n":"redraw","t":"redraw: Undecided => Draw","d":"cribbage.Cribbage","k":"def"},
{"l":"cribbage/model.html#","e":false,"i":"","n":"cribbage.model","t":"cribbage.model","d":"","k":"package"},
{"l":"cribbage/model/Card.html#","e":false,"i":"","n":"Card","t":"Card(face: Face, suit: Suit)","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Card$.html#","e":false,"i":"","n":"Card","t":"Card","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Card$.html#faces-0","e":false,"i":"","n":"faces","t":"faces: Array[Face]","d":"cribbage.model.Card","k":"val"},
{"l":"cribbage/model/Card$.html#rank-fffffba9","e":false,"i":"Card","n":"rank","t":"rank: Int","d":"cribbage.model.Card","k":"def"},
{"l":"cribbage/model/Card$.html#suits-0","e":false,"i":"","n":"suits","t":"suits: Array[Suit]","d":"cribbage.model.Card","k":"val"},
{"l":"cribbage/model/Card$.html#value-fffffba9","e":false,"i":"Card","n":"value","t":"value: Int","d":"cribbage.model.Card","k":"def"},
{"l":"cribbage/model/Card$$Face.html#","e":false,"i":"","n":"Face","t":"Face(val value: Int, val rank: Int)","d":"cribbage.model.Card","k":"enum"},
{"l":"cribbage/model/Card$$Face.html#Ace-0","e":false,"i":"","n":"Ace","t":"Ace extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Two-0","e":false,"i":"","n":"Two","t":"Two extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Three-0","e":false,"i":"","n":"Three","t":"Three extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Four-0","e":false,"i":"","n":"Four","t":"Four extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Five-0","e":false,"i":"","n":"Five","t":"Five extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Six-0","e":false,"i":"","n":"Six","t":"Six extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Seven-0","e":false,"i":"","n":"Seven","t":"Seven extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Eight-0","e":false,"i":"","n":"Eight","t":"Eight extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Nine-0","e":false,"i":"","n":"Nine","t":"Nine extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Ten-0","e":false,"i":"","n":"Ten","t":"Ten extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Jack-0","e":false,"i":"","n":"Jack","t":"Jack extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#Queen-0","e":false,"i":"","n":"Queen","t":"Queen extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Face.html#King-0","e":false,"i":"","n":"King","t":"King extends Face","d":"cribbage.model.Card.Face","k":"case"},
{"l":"cribbage/model/Card$$Suit.html#","e":false,"i":"","n":"Suit","t":"Suit","d":"cribbage.model.Card","k":"enum"},
{"l":"cribbage/model/Card$$Suit.html#Clubs-0","e":false,"i":"","n":"Clubs","t":"Clubs extends Suit","d":"cribbage.model.Card.Suit","k":"case"},
{"l":"cribbage/model/Card$$Suit.html#Diamonds-0","e":false,"i":"","n":"Diamonds","t":"Diamonds extends Suit","d":"cribbage.model.Card.Suit","k":"case"},
{"l":"cribbage/model/Card$$Suit.html#Hearts-0","e":false,"i":"","n":"Hearts","t":"Hearts extends Suit","d":"cribbage.model.Card.Suit","k":"case"},
{"l":"cribbage/model/Card$$Suit.html#Spades-0","e":false,"i":"","n":"Spades","t":"Spades extends Suit","d":"cribbage.model.Card.Suit","k":"case"},
{"l":"cribbage/model/Cards$.html#","e":false,"i":"","n":"Cards","t":"Cards","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Cards$.html#Crib-0","e":false,"i":"","n":"Crib","t":"Crib","d":"cribbage.model.Cards","k":"type"},
{"l":"cribbage/model/Cards$.html#Deck-0","e":false,"i":"","n":"Deck","t":"Deck","d":"cribbage.model.Cards","k":"type"},
{"l":"cribbage/model/Cards$.html#Hand-0","e":false,"i":"","n":"Hand","t":"Hand","d":"cribbage.model.Cards","k":"type"},
{"l":"cribbage/model/Cards$.html#addAll-fffff6c1","e":false,"i":"Crib","n":"addAll","t":"addAll(these: Seq[Card]): Crib","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#contains-10d","e":false,"i":"Hand","n":"contains","t":"contains(card: Card): Boolean","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#containsAll-40a","e":false,"i":"Hand","n":"containsAll","t":"containsAll(these: Seq[Card]): Boolean","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#containsAny-21a","e":false,"i":"Hand","n":"containsAny","t":"containsAny(rule: Card => Boolean): Boolean","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#cribOf-716","e":false,"i":"","n":"cribOf","t":"cribOf(cards: Seq[Card]): Crib","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#cut-fffff0dd","e":false,"i":"Deck","n":"cut","t":"cut: (Deck, Card)","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#deal-fffff7fd","e":false,"i":"Deck","n":"deal","t":"deal(numberOfHands: Int, cardsPerHand: Int): (Deck, Seq[Hand])","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#deckOf-716","e":false,"i":"","n":"deckOf","t":"deckOf(cards: Seq[Card]): Deck","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#emptyCrib-0","e":false,"i":"","n":"emptyCrib","t":"emptyCrib: Crib","d":"cribbage.model.Cards","k":"val"},
{"l":"cribbage/model/Cards$.html#emptyHand-0","e":false,"i":"","n":"emptyHand","t":"emptyHand: Hand","d":"cribbage.model.Cards","k":"val"},
{"l":"cribbage/model/Cards$.html#fullDeck-0","e":false,"i":"","n":"fullDeck","t":"fullDeck: Deck","d":"cribbage.model.Cards","k":"val"},
{"l":"cribbage/model/Cards$.html#handOf-716","e":false,"i":"","n":"handOf","t":"handOf(cards: Seq[Card]): Hand","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#isFull-b15","e":false,"i":"Crib","n":"isFull","t":"isFull: Boolean","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#remove-1e","e":false,"i":"Hand","n":"remove","t":"remove(card: Card): Hand","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#removeAll-fffff6c1","e":false,"i":"Hand","n":"removeAll","t":"removeAll(these: Seq[Card]): Hand","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#shuffledDeck-0","e":false,"i":"","n":"shuffledDeck","t":"shuffledDeck: Deck","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#size-fffff55c","e":false,"i":"Crib | Deck | Hand","n":"size","t":"size: Int","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Cards$.html#toSeq-716","e":false,"i":"Crib | Deck | Hand","n":"toSeq","t":"toSeq: Seq[Card]","d":"cribbage.model.Cards","k":"def"},
{"l":"cribbage/model/Discarding.html#","e":false,"i":"","n":"Discarding","t":"Discarding(deck: Deck, scores: Map[Player, Score], hands: Map[Player, Hand], dealer: Player, pone: Player, crib: Crib)","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Draw.html#","e":false,"i":"","n":"Draw","t":"Draw","d":"cribbage.model","k":"trait"},
{"l":"cribbage/model/Draw$.html#","e":false,"i":"","n":"Draw","t":"Draw","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Draw$$Decided.html#","e":false,"i":"","n":"Decided","t":"Decided(draws: Map[Player, Card], dealer: Player, pone: Player) extends Draw","d":"cribbage.model.Draw","k":"class"},
{"l":"cribbage/model/Draw$$Undecided.html#","e":false,"i":"","n":"Undecided","t":"Undecided(draws: Map[Player, Card]) extends Draw","d":"cribbage.model.Draw","k":"class"},
{"l":"cribbage/model/Finished.html#","e":false,"i":"","n":"Finished","t":"Finished(scores: Map[Player, Score])","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Player.html#","e":false,"i":"","n":"Player","t":"Player(id: UUID) extends AnyVal","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Player$.html#","e":false,"i":"","n":"Player","t":"Player","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Player$.html#newPlayer-0","e":false,"i":"","n":"newPlayer","t":"newPlayer: Player","d":"cribbage.model.Player","k":"def"},
{"l":"cribbage/model/Playing.html#","e":false,"i":"","n":"Playing","t":"Playing(scores: Map[Player, Score], hands: Map[Player, Hand], dealer: Player, pone: Player, crib: Crib, cut: Card, plays: Plays)","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Plays.html#","e":false,"i":"","n":"Plays","t":"Plays(nextPlayer: Player, inPlay: Seq[Play], played: Seq[Play])","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Plays$.html#","e":false,"i":"","n":"Plays","t":"Plays","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Plays$.html#allPassed-faf","e":false,"i":"Plays","n":"allPassed","t":"allPassed: Boolean","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#allPlaysCompleted-faf","e":false,"i":"Plays","n":"allPlaysCompleted","t":"allPlaysCompleted: Boolean","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#apply-92c","e":false,"i":"","n":"apply","t":"apply(player: Player): Plays","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#cardsInPlay-9bc","e":false,"i":"Plays","n":"cardsInPlay","t":"cardsInPlay: Seq[Card]","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#mustPass-f24","e":false,"i":"Plays","n":"mustPass","t":"mustPass(hand: Hand): Boolean","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#pass-83d","e":false,"i":"Plays","n":"pass","t":"pass(player: Player): Plays","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#play-d23","e":false,"i":"Plays","n":"play","t":"play(player: Player, card: Card): Plays","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#regather-2b9","e":false,"i":"Plays","n":"regather","t":"regather: Map[Player, Hand]","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#restarted-fffff422","e":false,"i":"Plays","n":"restarted","t":"restarted: Plays","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#runningTotal-6f6","e":false,"i":"Plays","n":"runningTotal","t":"runningTotal: Int","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$.html#withNextPlayer-83d","e":false,"i":"Plays","n":"withNextPlayer","t":"withNextPlayer(player: Player): Plays","d":"cribbage.model.Plays","k":"def"},
{"l":"cribbage/model/Plays$$Laid.html#","e":false,"i":"","n":"Laid","t":"Laid(player: Player, card: Card) extends Play","d":"cribbage.model.Plays","k":"class"},
{"l":"cribbage/model/Plays$$Pass.html#","e":false,"i":"","n":"Pass","t":"Pass(player: Player) extends Play","d":"cribbage.model.Plays","k":"class"},
{"l":"cribbage/model/Plays$$Play.html#","e":false,"i":"","n":"Play","t":"Play","d":"cribbage.model.Plays","k":"trait"},
{"l":"cribbage/model/Rule.html#","e":false,"i":"","n":"Rule","t":"Rule","d":"cribbage.model","k":"trait"},
{"l":"cribbage/model/Rule$.html#","e":false,"i":"","n":"Rule","t":"Rule","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Rule$$NonParticipatingPlayer.html#","e":false,"i":"","n":"NonParticipatingPlayer","t":"NonParticipatingPlayer(player: Player) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$NotYourTurn.html#","e":false,"i":"","n":"NotYourTurn","t":"NotYourTurn(player: Player) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$PlayTargetAttainable.html#","e":false,"i":"","n":"PlayTargetAttainable","t":"PlayTargetAttainable(player: Player) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$PlayTargetExceeded.html#","e":false,"i":"","n":"PlayTargetExceeded","t":"PlayTargetExceeded(player: Player, card: Card) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$TooManyDiscards.html#","e":false,"i":"","n":"TooManyDiscards","t":"TooManyDiscards(player: Player, cards: Seq[Card]) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$UnheldCard.html#","e":false,"i":"","n":"UnheldCard","t":"UnheldCard(player: Player, card: Card) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Rule$$UnheldCards.html#","e":false,"i":"","n":"UnheldCards","t":"UnheldCards(player: Player, cards: Seq[Card]) extends Rule","d":"cribbage.model.Rule","k":"class"},
{"l":"cribbage/model/Score.html#","e":false,"i":"","n":"Score","t":"Score(back: Int, front: Int)","d":"cribbage.model","k":"class"},
{"l":"cribbage/model/Score$.html#","e":false,"i":"","n":"Score","t":"Score","d":"cribbage.model","k":"object"},
{"l":"cribbage/model/Score$.html#add-827","e":false,"i":"Score","n":"add","t":"add(points: Int): Score","d":"cribbage.model.Score","k":"def"},
{"l":"cribbage/model/Score$.html#isWinningScore-bbc","e":false,"i":"Score","n":"isWinningScore","t":"isWinningScore: Boolean","d":"cribbage.model.Score","k":"def"},
{"l":"cribbage/model/Score$.html#points-183","e":false,"i":"Score","n":"points","t":"points: Int","d":"cribbage.model.Score","k":"def"},
{"l":"cribbage/model/Score$.html#zero-0","e":false,"i":"","n":"zero","t":"zero: Score","d":"cribbage.model.Score","k":"val"},
{"l":"cribbage/scorer.html#","e":false,"i":"","n":"cribbage.scorer","t":"cribbage.scorer","d":"","k":"package"},
{"l":"cribbage/scorer/Scorer$.html#","e":false,"i":"","n":"Scorer","t":"Scorer","d":"cribbage.scorer","k":"object"},
{"l":"cribbage/scorer/Scorer$.html#scoreHands-0","e":false,"i":"","n":"scoreHands","t":"scoreHands: Playing => Playing | Finished","d":"cribbage.scorer.Scorer","k":"val"},
{"l":"cribbage/scorer/Scorer$.html#scoreHisHeels-0","e":false,"i":"","n":"scoreHisHeels","t":"scoreHisHeels: Playing => Playing | Finished","d":"cribbage.scorer.Scorer","k":"val"},
{"l":"cribbage/scorer/Scorer$.html#scorePass-0","e":false,"i":"","n":"scorePass","t":"scorePass: Playing => Playing | Finished","d":"cribbage.scorer.Scorer","k":"val"},
{"l":"cribbage/scorer/Scorer$.html#scorePlay-0","e":false,"i":"","n":"scorePlay","t":"scorePlay: Playing => Playing | Finished","d":"cribbage.scorer.Scorer","k":"val"},
{"l":"cribbage/styling.html#","e":false,"i":"","n":"cribbage.styling","t":"cribbage.styling","d":"","k":"package"},
{"l":"cribbage/styling/Styling$.html#","e":false,"i":"","n":"Styling","t":"Styling","d":"cribbage.styling","k":"object"},
{"l":"cribbage/styling/Styling$.html#styled-fffff3a3","e":false,"i":"Card","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-a90","e":false,"i":"Crib | Deck | Hand","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-fffff1c0","e":false,"i":"Player","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-489","e":false,"i":"Score","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-9d4","e":false,"i":"Play","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-fffff7b6","e":false,"i":"Plays","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-897","e":false,"i":"Discarding","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-fffff1a5","e":false,"i":"Playing","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$.html#styled-fffffe05","e":false,"i":"Finished","n":"styled","t":"styled: String","d":"cribbage.styling.Styling","k":"def"},
{"l":"cribbage/styling/Styling$$Ansi$.html#","e":false,"i":"","n":"Ansi","t":"Ansi","d":"cribbage.styling.Styling","k":"object"},
{"l":"cribbage/styling/Styling$$Ansi$.html#escape-0","e":false,"i":"","n":"escape","t":"escape: String","d":"cribbage.styling.Styling.Ansi","k":"val"},
{"l":"cribbage/styling/Styling$$Ansi$.html#reset-0","e":false,"i":"","n":"reset","t":"reset: String","d":"cribbage.styling.Styling.Ansi","k":"val"}];