[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
domain = { path = "../domain", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.16.0", features = ["v4", "serde", "js"] }
rand = { version = "0.8.5", optional = true }
rand_chacha = { version = "0.3.1", optional = true }
goofy-animals = { version = "0.0.2", optional = true }
sqlx = { version = "0.8.5", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "migrate",
], optional = true }
thiserror = "2.0.12"
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = { version = "1.0.140", optional = true }
redis = { version = "0.31", features = [
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio = { version = "1.45.0", features = ["full"], optional = true }
futures = "0.3.31"
async-stream = "0.3.6"
http = "1.3.1"

[features]
default = []
web = ["dioxus/web"]
server = [
    "dioxus/server",
    "dep:domain",
    "dep:goofy-animals",
    "dep:rand",
    "dep:rand_chacha",
    "dep:redis",
    "dep:serde_json",
    "dep:sqlx",
    "dep:tokio",
]

[lints]
clippy.all = "deny"
clippy.nursery = "warn"
clippy.unwrap_used = "forbid"
clippy.expect_used = "deny"
