name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    docker:
        name: Start Docker services
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: postgres://postgres:password@localhost:5432/cribbage
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            # - name: Setup docker compose
            #   uses: docker/setup-compose-action@v1

            - name: Setup containers
              shell: bash
              run: |
                  pwd
                  ls -al
                  docker compose -f docker/docker-compose up -d
                  cd packages/server
                  sqlx migrate run

    qa:
        needs: [docker]
        uses: nigeleke/github/.github/workflows/dioxus-qa.yml@main
        with:
            platform: web
            env: '{ "DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/postgres" }'

    bundle:
        needs: [qa]
        uses: nigeleke/github/.github/workflows/dioxus-bundle.yml@main
        with:
            platform: web
